language: python
sudo: enabled

python:
  - "2.7"
  - "3.6"

before_install:
  - sudo useradd test -m -s /bin/bash -G travis
  - (echo 'test'; echo 'test') | sudo passwd test

install:
  # Install ssh tunnel library.
  - python setup.py install
  # to See what are the packages are installed
  - pip freeze

script:
  - py.test -v -rs test